name: DiffSynthStudio
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.9.16
  - pip=23.0.1
  - cudatoolkit
  - pytorch
  - cupy
  - pip:
    - transformers
    - controlnet-aux==0.0.7
    - streamlit
    - streamlit-drawable-canvas
    - imageio
    - imageio[ffmpeg]
    - safetensors
    - einops
    - sentencepiece
